### ISSUE TITLE
Cancelling a drop

### ISSUE THREAD

**Issue by Spodnet** [johnny/jquery-sortable#1]
Is it possible to cancel a drop if it's not required.

I'm trying to do it by taking a copy of the object onDrag, then onDrop check if the item is in the right place (in my case, I only want certain items to be in the root ul, and not nested).

Is it possible to stop a drop happening and reset the item that's dragged ?

**Comment by JgoOrange** [comment]
Hi There I am having the same type of issue where onDrop if values are met them the drop is rejected but cannot get the ol to revert back to its original position i have tried the above code but think the issue is that it is already inside  of a sortable call. and help would be great.

          `$("ol.left").sortable({
		group: 'nested',
		onDrop: function (event, ui){
			var $this = $('.active');
			var li = $this.parents('li');
                        var ol = $this.parents('ol').parents('ol');
			var div = $this.closest('div');
			li.removeClass("dragged");
			li.removeAttr('style');
                 if (($(div).hasClass('left')) && ($(ol).hasClass('left'))) {
                     alert("test");  //code to revert goes here
                 } else {
                     update_fs();
                 }
		         }
	});`
