### ISSUE TITLE
using sortable prevents bind clicks on children on iPad

### ISSUE THREAD

**Issue by Elrinth** [johnny/jquery-sortable#161]
Warning if you intend to use this plugin and have clickable childrens it will not work!
I wanted to use this plugin to sort images which have a clickable enlarge icon on them. But the onclick for the enlarge icon will never work on iPad browser.

**Comment by johnny** [comment]
I am not sure what to make of this. You don't seem to have the intention to fix this, so why open this issue at all?
I would suggest you read up on event bubbling. Your problem is almost certainly solvable.
