### ISSUE TITLE
Position relative breaks nested sortable reordering - please fix or help!

### ISSUE THREAD

**Issue by roartex** [johnny/jquery-sortable#162]
Hi there,

I'm using this plugin as a base for the drag and drop part of a web editor I am making. Some of the elements that can be dragged around with this plugin need to have position relative applied to them as they have absolutely positioned elements inside.

But currently, the reordering of this plugin breaks when position relative is added to the list items. This can be reproduced easily on the demo page if you just add position relative to the <li> elements in the inspector window of your browser.

Top level reodering still works just fine, but nested reordering breaks. 

Could anybody help with this? 

Thank you in advance!

**Comment by roartex** [comment]
Fiddle here: http://jsfiddle.net/0ogreec0/1/

**Comment by johnny** [comment]
Relative positioning won't work, since this breaks nested sorting.

An alternative I have been thinking about is using css transforms. But I havn't started work on this.
