### ISSUE TITLE
Long table cell contents during drag

### ISSUE THREAD

**Issue by obdf** [johnny/jquery-sortable#163]
I don't know if this has been answered before but I have a table that has some very long text in one of the cells (description).  The table is using ellipsis to shorten the text while maintaining a responsive layout.  When a TR with long text is dragged, the text is fully expanded in the 'draggable' copy that moves, and as a result the element is completely out of sorts - shadow is off a whole row, and the bottom border is off by the height of a row.  I think this is clearly happening due to the long text...  does anyone know how to handle this?  Either by shortening the text during drag or fixing the width of the dragging element?

**Comment by johnny** [comment]
The ellipsis is only in effect, when the cell has a restricted width. Dragging the row probably removes some restrictions on the cell width, hence all the text is being displayed.
You will need to set the width of the cells or the row to the current value before dragging.
On drop, remove these additional css values to make the row responsive again.

Please report back, if this worked for you.

**Comment by obdf** [comment]
Thanks ... it looks like this worked..  since the long field is the third column in my table..

$('.sorted-table').sortable({
  containerSelector: 'table',
  itemPath: '> tbody',
  itemSelector: 'tr',
  placeholder: '<tr class="placeholder"/>',
  onDragStart: function($item, container, _super) {
    var description = $item.find("td")[2];
    $item.find(description).css("max-width", 
                                $item.find(description).width() + "px");
    _super($item, container)
  }
})

**Comment by obdf** [comment]
And thanks for the great plugin!!!!   Saved us what I would guess is a few days!!
