### ISSUE TITLE
Sort question

### ISSUE THREAD

**Issue by pominglam** [johnny/jquery-sortable#165]
This library looks really good. In the main example, you show nested vertical sortable items. Can I have items that are not 100% width and with some left or right to each other while some are above or below?

I guess it's like having vertical and horizontal at the same time, and with nested sortable lists.

Is this currently supported? If so, can you give me an example of code please?

Thanks!

**Comment by johnny** [comment]
If you want to sort one big grid, the answer is: no, that is currently not supported, since that is a different use case which is hart to get right.
If you are fine with either independent columns or independent rows, the answer is yes. But it will require some work around the plugin

**Comment by pominglam** [comment]
Alright, thanks Johnny! Although your plugin might not serve my current use case, your nested sorting is still awesome!

**Comment by johnny** [comment]
Your welcome. Closing this then
