### ISSUE TITLE
Example: Visual programing editor

### ISSUE THREAD

**Issue by ycatch** [johnny/jquery-sortable#166]
Thanks jonnny.  jquery-sortable is great library.

I will introduce one example.
SoraMame.Block is simple visual programing editor for tiny script like a Scratch or Blockly.
 I wrote just only 100 lines Javascript code with jquery-sortable.

Source
 https://github.com/ycatch/SoraMame.Block
Demo 1: you can edit simple FizzBuzz code on your browser.
 http://www.catch.jp/program/soramame_block/
Demo 2: mini game
 http://www.catch.jp/program/soramame_block/example_game.html

Please check this.

**Comment by johnny** [comment]
That looks nice. I added it to the examples section: https://johnny.github.io/jquery-sortable/#external

Thanks a lot!
