### ISSUE TITLE
Please update jquery-sortable version number

### ISSUE THREAD

**Issue by mrbinky3000** [johnny/jquery-sortable#167]
Running bower install jquery-sortable pulls in tag 0.9.12 but that tag has no bower.json file and hence, no "main" config option.

The master branch has the new bower.json file, but bower install grabs the latest tag by default, not master.

It's breaking projects where jquery-sortable is a dependency.

just make a new tag from master, call it 0.9.13   problem solved

Thanks!

**Comment by brunowego** [comment]
+1

**Comment by wefarrell** [comment]
+1

**Comment by johnny** [comment]
just released 0.9.13
