### ISSUE TITLE
Is there a specific reason that jquery-sortable uses the same 'sortable' plugin name as jQuery UI's sortable?

### ISSUE THREAD

**Issue by dhilowitz** [johnny/jquery-sortable#171]
I'm asking because I would like to have both be available to my project and use yours for some things and the jQuery UI sortable plugin for other things. If I were to change the last line of jquery-sortable.js to read `(jQuery, window, 'jQuerySortable');` or something like that, would anything break? 

Thanks!

**Comment by johnny** [comment]
Your proposed change should work.
