### ISSUE TITLE
Table Cols not sortable ... fix?

### ISSUE THREAD

**Issue by dirkdirk** [johnny/jquery-sortable#173]
I have tables with many cols and the js as provided in the example only seems to work consistently on tables with 2 cols.

I rewrote onDrop to the following that seems to be working consistently:

		onDrop: function ($item, container, _super) {
			var field;
			var newIndex = $item.index();

			if(newIndex != oldIndex) {
				$item.closest('table').find('tbody tr').each(function (i, row) {
					row = $(row);
					if(newIndex < oldIndex) {
						row.children().eq(newIndex).before(row.children()[oldIndex]);
					} else if (newIndex > oldIndex) {
						row.children().eq(newIndex).after(row.children()[oldIndex]);
					}
				})
			}
			_super($item, container);
		}

Comments?

**Comment by johnny** [comment]
Looking good. You can find it on the website now: https://johnny.github.io/jquery-sortable/#table
