### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by katiabaer** [johnny/jquery-sortable#181]
on this page https://johnny.github.io/jquery-sortable/
3rd example :  
onDrop: function (item, container, _super) {
    container.el.removeClass("active")
    _super(item)
  }
doesn't work, getting an error on this line:       $item.removeClass(container.group.options.draggedClass).removeAttr("style")
"container is undefined"

had to change to 

onDrop: function (item, container, _super) {
    container.el.removeClass("active")
    _super(item,container)
  }

**Comment by johnny** [comment]
fixed in master
