### ISSUE TITLE
Disabling dragging of single items

### ISSUE THREAD

**Issue by ghost** [johnny/jquery-sortable#66]
Firstly, thanks for a great library.

I can't find a way to disable the dragging of single items, I've tried the following but it doesn't work:

``` javascript
{
    onMouseDown: function(item, event, _super) {
      if (item.hasClass('no-drag')) {
        event.preventDefault();
      } else {
        _super(item);
      }
    }
}
```

Any pointers would be most welcome.

**Comment by saad024** [comment]
hi.. is that possible to make item sortable in same list but not dragable to another list??
