### ISSUE TITLE
Prevent Children from moving out of Parent (?)

### ISSUE THREAD

**Issue by Bratzilla** [johnny/jquery-sortable#76]
Hello. I apologize in advance if this is documented and I just couldn't find it.

I have a project where I was originally using jQuery UI sortable. It worked, but I use so little of the library that I just cannot justify the weight. So,  I need an alternative drag-and-drop solution for categories in a system where there is no nesting limit, and where categories can, if enabled to, have any number of children.

To keep it simple, I want to be able to drag/drop/sort sibling categories within their parent. Children cannot exit out of their parent categories, and, if a category with children is moved, all the children go with it.

In my structure, children are bound by the container ul class="children". So, each group of "children" (siblings) are bound by an unordered list with that class. 

I tried combing through the documentation but couldn't find an obvious solution. I've set up the following fiddle for testing (and it provides a far better visual than what I can describe here):

http://jsfiddle.net/WM64K/74/

If anyone could tell me how to go about doing this, or if there is some other documentation I could read, I would really appreciate it. Thanks!

**Comment by jrawaldhiya-lightbox** [comment]
Hello friends,

I am new to jQuery UI, and need to implement similar kind of functionality for table of contents. I have tried the code provided in http://jsfiddle.net/WM64K/91/ but it is not working for me.

Can you please let me know what I am missing here.
Thank You
Jai
